// 全局设置
export const SETDEVICE = "SETDEVICE";
export const SETTHEME = "SETTHEME";
export const SETLAYOUT = "SETLAYOUT";
export const SETMULTIPAGE = "SETMULTIPAGE";
// 登录
export const CHANGELOGINSTATUS = "CHANGELOGINSTATUS";
// cup 有料 -- begin
// 标签管理
export const GETTAGS = "GETTAGS";
export const CHANGETAGATTR = "CHANGETAGATTR";
export const GETALLTAGS = "GETALLTAGS";
// 文章管理
export const GETARTICLES = "GETARTICLES";
export const CHANGEARTICLESATTR = "CHANGEARTICLESATTR";
export const GETARTICLEDETAIL = "GETARTICLEDETAIL";
// 数据统计
export const GETCUPSTATISTICS = "GETCUPSTATISTICS";
export const GETCUPCOLLECTS = "GETCUPCOLLECTS";
// cup 有料 -- end

// 社区活动 --beigin
// 活动管理
export const GETACTIVITIES = "GETACTIVITIES";
export const CHANGEACTIVITYATTR = "CHANGEACTIVITYATTR";
export const GETACTIVITYDETAIL = "GETACTIVITYDETAIL";
export const GETALLACTIVITIES = "GETALLACTIVITIES";
// 数据统计
export const GETCOMMUNITYSTATISTICS = "GETCOMMUNITYSTATISTICS";
// 报名管理
export const GETSIGNUPLIST = "GETSIGNUPLIST";
// 社区活动 --end

// 体态训练营 --beigin
// 分类管理
export const GETCATEGORY = "GETCATEGORY";
export const CHANGECATEGORYATTR = "CHANGECATEGORYATTR";
export const GETALLCATEGORYIES = "GETALLCATEGORYIES";
// 体态测评
export const GETEVALUATIONS = "GETEVALUATIONS";
// 课程管理
export const GETCOURSES = "GETCOURSES";
export const CHANGECOURSESATTR = "CHANGECOURSESATTR";
export const GETCOURSEDETAIL = "GETCOURSEDETAIL";
// 分解图
export const GETDIAGRAMS = "GETDIAGRAMS";
export const CHANGEDIAGRAMSATTR = "CHANGEDIAGRAMSATTR";
// 数据统计
export const GETCOURSESTATISTICS = "GETCOURSESTATISTICS";
export const GETCOURSEJOINS = "GETCOURSEJOINS";

// 体态训练营 -- end

// 专家管理 -- begin
export const GETALLEXPERTS = "GETALLEXPERTS";
export const GETEXPERTS = "GETEXPERTS";
export const CHANGEEXPERTSATTR = "CHANGEEXPERTSATTR";
// 专家管理 -- end

// 商品管理 -- begin
export const GETALLGOODS = "GETALLGOODS";
export const GETGOODS = "GETGOODS";
export const GETGOODSINFO = "GETGOODSINFO";
// 商品管理 -- end
// 广告位管理
export const GETBANNERS = "GETBANNERS";
export const CHANGEBANNERATTR = "CHANGEBANNERATTR";
// 广告位管理 -- end

//弹窗管理
export const GETPOPUPS = "GETPOPUPS";
export const CHANGEPOPUPATTR = "CHANGEPOPUPATTR";
//弹窗管理 -- end

//海报管理
export const GETPOSTERS = "GETPOSTERS";
export const CHANGEPOSTERATTR = "CHANGEPOSTERATTR";
//海报管理 -- end

//首页管理
export const GETMENUS = "GETMENUS";
export const CHANGEMENUATTR = "CHANGEMENUATTR";

//用户权益
export const GETUSERBENEFITS = "GETUSERBENEFITS";

//分享管理
export const GETSHARE = "GETSHARE";

//会员管理
export const GETMEMBERS = "GETMEMBERS";
export const GETUSERSPOUSE = "GETUSERSPOUSE";
export const GETUSERBABY = "GETUSERBABY";
export const GETUSERINTEGRAL = "GETUSERINTEGRAL";
export const GETUSERACTIVITYS = "GETUSERACTIVITYS";
export const GETUSERFIELDS = "GETUSERFIELDS";
export const GETCOUPONTEMPLATES = "GETCOUPONTEMPLATES";
export const GETUSERREGCONFIG = "GETUSERREGCONFIG";
export const GETUSERINFOCONFIG = "GETUSERINFOCONFIG";
export const GETUSERINVITECONFIG = "GETUSERINVITECONFIG";
export const GETUSERINTEGRALRULE = "GETUSERINTEGRALRULE";
export const CHANGEUSERINTEGRALRULEATTR = "CHANGEUSERINTEGRALRULEATTR";
export const GETUSERINTEGRALFLOW = "GETUSERINTEGRALFLOW";
export const GETCOUPONS = "GETCOUPONS";
export const GETUSERACTIVITYCONFIG = "GETUSERACTIVITYCONFIG";
export const GETUSERGUIDE = "GETUSERGUIDE";
//互动统计
export const GETUSERBEHAVIOR = "GETUSERBEHAVIOR";

export const GETALLPAGES = "GETALLPAGES";